### ISSUE TITLE
Design high-level spec

### ISSUE THREAD

**Issue by joshtemple** [dbanalyticsco/Fonz#2]
@DylanBaker, writing down my thoughts in this issue which we can use for our initial design and division of work. Happy to break this up into separate issues as well if that's easier. Let me know what you think!

## User interface

Right now I'm envisioning two CLI commands, one to run the content validator `fonz content` and one to run the queries to check for database errors `fonz sql` (naming quite obviously open to feedback).

### Start a new development mode session
Documentation: [Session > Update Session](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/session#update_session)

It's not entirely clear how to do this, I don't see the specification for the request in the documentation, but this seems to be the right endpoint to switch from prod to dev mode. This endpoint is also in beta so is subject to change.

Some other relevant information from the Workspace documentation [here](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/workspace#get_workspace):
>The dev workspace is local to each Looker user. Changes made to project/model files in the dev workspace only affect that user, and only when the dev workspace is selected as the active workspace for the API session. (See set_session_workspace()).

>The dev workspace is NOT unique to an API session. Two applications accessing the Looker API using the same user account will see the same files in the dev workspace. To avoid collisions between API clients it’s best to have each client login with API3 credentials for a different user account.

>Changes made to files in a dev workspace are persistent across API sessions. It’s a good idea to commit any changes you’ve made to the git repository, but not strictly required. Your modified files reside in a special user-specific directory on the Looker server and will still be there when you login in again later and use update_session(workspace_id: “dev”) to select the dev workspace for the new API session.

### Check out branch
Documentation: [Projects > Checkout New Git Branch](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/project#checkout_new_git_branch)

### Parse LookML

Documentation: [LookmlModel > Get LookML Model](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/lookml-model#get_lookml_model)

The idea here is to download the names of all fields from each explore and store them by explore name for later querying.

### Build a query

Documentation: [Query > Create Query](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/query#create_query)

Looker queries have to be created before they can be run. Here's where we pass all of the fields, model name, and view name to construct our query for a given explore.

### Run a query

Documentation: [Query > Run Query](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/query#run_query)

### Run content validation

Documentation: [Content > Validate Content](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/content#validate_content)

This is an API 3.1 only endpoint (currently in beta status) and also requires the Content Validation Labs Feature to be enabled. Maybe we make this more of a stretch goal since the Looker features required here seem less stable.

There's an example of how to use this in Looker's [Python API sample code repo](https://github.com/llooker/python_api_samples/blob/master/run_content_validator.py).

## Python class design
Stubbing out a rough draft of the core class and important methods.

```
from typing import Sequence, List, Dict, Any

JsonDict = Dict[str, Any]


class Fonz:
    def __init__(client_id: str, client_secret: str, branch: str):
        """Instantiate Fonz and save authentication details and branch."""
        self.client_id = client_id
        self.client_secret = client_secret
        self.branch = branch

    def connect(branch: str) -> None:
        """Authenticate, start a dev mode session, check out specified branch."""

    def get_dimensions(explore: str) -> List[str]:
        """Get dimensions for a specified explore from the LookmlModel endpoint."""

    def create_query(dimensions: Sequence) -> str:
        """Build a Looker query using all the specified dimensions."""

    def run_query(query_id) -> JsonDict:
        """Run a Looker query by ID and return the JSON result."""

    def validate_content() -> JsonDict:
        """Validate all content and return any JSON errors."""
```

**Comment by DylanBaker** [comment]
Hey 👋. This is awesome. My notes, is no particular order:

### Passing argument

On the CLI commands, those two definitely make sense. I think there are four things that would need to be passed in the run:

* URL
* Client ID
* Client Secret
* Development Branch

The first three are likely to always be the same, whereas the fourth is likely to change on each call. Do you have any preference thoughts on declaration? (I see the three options as in a config file, as an environment variable, and as a CLI argument.) I think any of those could work for the first three. For the development branch, I think a file is least useful as it would be the most difficult way to dynamically change.

### Additional Connect command

I think it would be good to have a `connect` command, to give people the ability to test their credentials.

### Getting into a `dev` environment.

I'm slightly confused by the [Workspace](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/workspace) and [Session](https://docs.looker.com/reference/api-and-integration/api-reference/v3.0/session#update_session) API docs. 

From the docs:

> There are two predefined workspaces available: “production” and “dev”.

There are endpoints to GET all the workspaces, but it doesn't really explain whether you can have any workspaces other than those two. There isn't one to create a workspace (and I'm not aware of a way of doing it in the UI.)

All that to say, yes, I think you're right about the Session endpoint being the correct one. I _think_ we just need to hit it with `dev` and it should switch over. 

### 3.0 vs 3.1

Have you worked with the 3.1 API yet? I haven't, though at the Hackathon last week they were strongly pushing us to use it. 

It feels like using 3.1 is the thing we should do for future-proofing, but it means we can't use the pypi `lookerapi` package (which make not be a huge loss anyway). 

Another alternative is that we let the user control which one to use (particularly as if they are self-hosted they could still be on an old one) but we would need to add extra logic for that. 

### Endpoints and Class structure

Otherwise, this all looks good to me. Makes complete sense.  Do you have an idea as to how you think we could break up the development? 

### Testing

One thing I have not done a huge amount of before is testing external APIs. I'd love to do testing really well on this. (It seems hypocritical to not do so). We will need to mock the APIs, which I haven't done but am keen to learn. Have you got any experience there?
